source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MyFramework_Example', :exclusive => true do
  pod 'MyFramework', :path => '../'
end

target 'MyFramework_Tests', :exclusive => true do
  pod 'MyFramework', :path => '../'

  
end
